#!/bin/bash
START=$(date +%s)
cd kernel/
echo "[*]-------->>>> Compiling Kernel..."
ARCH=arm CROSS_COMPILE=/home/doomlord/android-toolchain-eabi/bin/arm-eabi- make -j8
END=$(date +%s)
ELAPSED=$((END - START))
E_MIN=$((ELAPSED / 60))
E_SEC=$((ELAPSED - E_MIN * 60))
echo -n "[*]-------->>>> "
printf "Elapsed: "
[ $E_MIN != 0 ] && printf "%d min(s) " $E_MIN
printf "%d sec(s)\n" $E_SEC
